on:
  push:
    tags:
      - 'v*'

name: Create Release

jobs:
  build:
    name: Create Release
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.0.x'
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        shell: pwsh 
        run: |
          dotnet build --configuration Release --no-restore
          Compress-Archive bin/Release/net6.0-windows/* autoupdater-test.windows-amd64.zip
          ((Get-Content -path ./update.xml -Raw) -replace '{{VERSION}}','${GITHUB_REF_NAME}') | Set-Content -Path ./update.xml
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          body: Please refer to CHANGELOG.md for details.
          draft: false
          prerelease: false
      - name: Upload Release Artifacts
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./autoupdater-test.windows-amd64.zip
          asset_name: autoupdater-test.windows-amd64.zip
          asset_content_type: application/zip
      - name: Upload Update Artifacts
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./update.xml
          asset_name: update.xml
          asset_content_type: application/xml